version: '3.8'

services:
  sound_to_script_bot:
    container_name: sound_to_script_bot
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    volumes:
      - ../data:/app/data
      - ../temp:/app/temp
    env_file:
      - ../.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 